- name: mysql setup
  hosts: all
  become: yes
  tasks:
    - name: copy mysql repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    - name: install mysql community server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    - name: enable & restart the mysql
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes
    - name: set mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}


  echo -e "${colour} cp mysql.repo \e[0m"
  cp mysql.repo /etc/yum.repos.d/mysql.repo &>>log_file
  status_check
  echo -e "${colour} Installing the nginx \e[0m"
  dnf install mysql-community-server -y &>>log_file
  status_check
  echo -e "${colour} enable the mysql \e[0m"
  systemctl enable mysqld &>>log_file
  status_check
  echo -e "${colour} start the mysqld \e[0m"
  systemctl start mysqld &>>log_file
  status_check
  echo -e "${colour} setting the password for db \e[0m"
  mysql_secure_installation --set-root-pass ${MYSQL_ROOT_PASSWORD} &>>log_file
  status_check
